---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: clear the environment
    file: 
      name: petclinic.war
      state: absent

  - name: download package from artifactory server
    command: 'curl -uuser1:APe8TNpyXKCb8VLuunDCEJcab2 -O -L "https://ganeshpalnitkar.jfrog.io/artifactory/Helloworldapp-repo/petclinic.war"'

- hosts: appservers
  remote_user:
  tasks:
  - name: deploy war file to server
    copy: 
      src: './petclinic.war'
      dest: '/opt/tomcat/webapps/petclinic.war'
 
  - name: start app server
    command: 'sh /opt/tomcat/bin/catalina.sh start'

