---

- name: manage webserver
  hosts: all
  gather_facts: true
  connection: local
  become: true
  tasks:
    - name: collect facts
      setup:
           filter: ansible_distribution
    - name: deploy file
      copy:
           src: "{{site_file}}"
           dest: "{{target_folder}}"
    - name: clone repo
      git:
           repo: 'https://github.com/ganeshhp/ansible-code.git'
           dest: /home/user/checkout
           clone: yes
           update: yes
    - name: manage users
      users:
           name: "{{username}}"
           state: present
