---

- name: manage webserver
  hosts: all
  gather_facts: true
  remote_user: user
  connection: local
  become: true
  tasks:
    - name: manage package
      yum:
          name: "{{package_name}}" 
          state: present
      use_backend: yum3
    - name: manage service
      service:
          name: "{{service_name}}"
          state: started 
    - name: deploy site
      copy:
          src: index.html
          dest: "{{doc_root}}"

