---

- name: manage webserver
  hosts: all
  gather_facts: true
  connection: local
  become: true
  tasks:
    - name: collect facts
      setup:
           filter: ansible_distribution
    - name: deploy file
      copy:
           src: index.html
           dest: /home/user/.
    - name: clone repo
      git:
           repo: 'https://github.com/ganeshhp/ansible-code.git'
           dest: /home/user/checkout
           clone: yes
           update: yes
           
